<div class="field is_superhero required">
    <div class="control">
        <input type="checkbox" name="is_superhero" id="is_superhero" value="1" title="<?php /* @escapeNotVerified */
        echo __('Superhero') ?>" class="input-text" data-validate="{required:true}">
        <label for="is_superhero" class="label"><span><?php /* @escapeNotVerified */
            echo __('Superhero') ?></span></label>
    </div>
</div>